apiVersion: v1
kind: Secret
metadata:
  name: {{ include "verify-container.fullname" . }}-db-credentials
  labels:
    {{- include "verify-container.labels" . | nindent 4 }}
type: Opaque
stringData:
  source-username: |-
    {{ .Values.secrets.credentials.sourceUsername }}
  destination-username: |-
    {{ .Values.secrets.credentials.destinationUsername }}
  destination-password: |-
    {{ .Values.secrets.credentials.destinationPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "verify-container.fullname" . }}-db-tls
  labels:
    {{- include "verify-container.labels" . | nindent 4 }}
type: Opaque
stringData:
  source-ca.crt: |-
{{ .Values.secrets.tls.sourceCaPem | nindent 4 }}
  source-client.crt: |-
{{ .Values.secrets.tls.sourceClientCertPem | nindent 4 }}
  source-client.key: |-
{{ .Values.secrets.tls.sourceClientKeyPem | nindent 4 }}
  destination-ca.crt: |-
{{ .Values.secrets.tls.destinationCaPem | nindent 4 }}
