listener:
  bind_addr: 0.0.0.0:18081
verify:
  raw_table_output: true
  source:
    url: postgresql://verify_no_select@localhost:16432/verify_report?sslmode=disable
  destination:
    url: postgresql://root@localhost:26262/verify_report?sslmode=disable
