apiVersion: v1
kind: Service
metadata:
  name: verify-container
  labels:
    app.kubernetes.io/name: verify-container
    app.kubernetes.io/component: verify-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: verify-container
    app.kubernetes.io/component: verify-service
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
