name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.22"

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      COVER_OUT: coverage.out

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up dependencies
        run: ./scripts/e2etest-setup.sh

      - name: Run E2E Tests
        run: |
          echo "current commit SHA: ${{ github.event.pull_request.head.sha }}"
          go test -v -timeout 30m ./e2e -e2e-enabled
        env:
          ENTERPRISE_ORG: ${{ vars.ENTERPRISE_ORG }}
          ENTERPRISE_LICENSE: ${{ secrets.ENTERPRISE_LICENSE }}
