name: Nix CI

on:
  pull_request:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    name: validate
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix run .#check
      - run: nix run .#test

  image:
    name: image-${{ matrix.image }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - runner-image
          - verify-image
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build ".#${{ matrix.image }}"
